FROM golang:1.22.8

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY .env.compose .env
COPY . .

RUN go build -o /bin/producer ./bin/producer/main.go

EXPOSE 8080

CMD ["producer"]
